services:
    sonata.page.admin.block:
            class: %sonata.page.admin.block.class%
            tags:
                - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: sonata_page, label_catalogue: %sonata.page.admin.page.translation_domain%, label: block, label_translator_strategy: sonata.admin.label.strategy.underscore }
            arguments: [ null, %sonata.page.admin.block.entity%, %sonata.page.admin.block.controller%, @kernel ]
            calls:
                - [ setCacheManager, [@sonata.cache.manager] ]
                - [ setBlockManager, [@sonata.block.manager] ]
                - [ setTranslationDomain, [%sonata.page.admin.block.translation_domain%] ]
                - [ setContainerBlockTypes, [%sonata.block.container.types%] ]
                - [ setFormTheme, [[SonataPageBundle:Form:form_admin_fields.html.twig, SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig]] ]

    orangegate.page.admin.languageversion:
        class: Symbio\OrangeGate\PageBundle\Admin\LanguageVersionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label: languageVersions }
        arguments: [null, Symbio\OrangeGate\PageBundle\Entity\LanguageVersion, null, @sonata.page.route.page.generator]
        calls:
            - [ setTranslationDomain, [ SonataPageBundle ] ]

    orangegate.page.admin.redirect:
        class: Symbio\OrangeGate\PageBundle\Admin\RedirectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label: redirect, label_catalogue: %sonata.page.admin.page.translation_domain%, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments: [null, Symbio\OrangeGate\PageBundle\Entity\Redirect, null]
        calls:
            - [ setTranslationDomain, [ SonataPageBundle ] ]

    orangegate.security.access.page_voter:
        class: Symbio\OrangeGate\PageBundle\Security\Authorization\Voter\PageVoter
        arguments: [ @service_container ]
        public: false
        tags:
           - { name: security.voter }

    orangegate.security.access.block_voter:
        class: Symbio\OrangeGate\PageBundle\Security\Authorization\Voter\BlockVoter
        arguments: [ @service_container ]
        public: false
        tags:
           - { name: security.voter }

    orangegate.page.form.type.page_selector:
        class: Symbio\OrangeGate\PageBundle\Form\Type\PageSelectorType
        arguments: [ @sonata.page.manager.page, @security.context ]
        tags:
            - { name: form.type, alias: orangegate_page_selector }

    orangegate.site.pool:
        class: Symbio\OrangeGate\PageBundle\Entity\SitePool
        arguments: [ @sonata.page.manager.site, @session ]

    orangegate.page.kernel.exception_listener:
        class: Symbio\OrangeGate\PageBundle\Listener\ExceptionListener
        arguments: [@sonata.page.site.selector, @sonata.page.cms_manager_selector, %kernel.debug%, @templating, @sonata.page.page_service_manager, @sonata.page.decorator_strategy, [], @logger, @security.token_storage, @sonata.admin.pool ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -126 }
            - { name: monolog.logger, channel: request }

    orangegate.page.repository.redirect:
        class:           Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ Symbio\OrangeGate\PageBundle\Entity\Redirect ]

    sonata.page.request_listener:
        class: %sonata.page.request_listener.class%
        scope: request
        arguments: [ @sonata.page.cms_manager_selector, @sonata.page.site.selector, @sonata.page.decorator_strategy, @orangegate.page.repository.redirect ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: 30 }
